# fly.toml app configuration file generated for recipe-extractor-api on 2025-05-27T14:36:30+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipe-extractor-api'
primary_region = 'syd'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  TRUST_PROXY_HOPS = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 20
    hard_limit = 40

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
