# fly.toml app configuration file generated for recipe-extractor-api on 2025-05-27T14:36:30+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipe-extractor-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
